version: '3.8'
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 5434:5432
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container
